name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  BuildTesting:
    runs-on: ubuntu-24.04

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: 1StrongPwd!!

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
          
    steps:
      - name: Realizando a busca do código-fonte
        uses: actions/checkout@v4

      - name: Configurando a versão .NET do projeto
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Instalando as dependências
        run: dotnet restore

      - name: Compilando o projeto
        run: dotnet build

      - name: Executando testes unitários
        run:   dotnet test ./UnitTests/UnitTests.csproj

      - name: Executando testes de integração
        run:  dotnet test --logger "console;verbosity=detailed" ./IntegrationTestsV2/IntegrationTestsV2.csproj

      - name: Mensagem final
        run: echo Integração finalizada com sucesso
